-- MySQL Script generated by MySQL Workbench
-- Sun Jan 20 00:40:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema semestralka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema semestralka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `semestralka` DEFAULT CHARACTER SET utf8 ;
USE `semestralka` ;

-- -----------------------------------------------------
-- Table `semestralka`.`vyrobce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestralka`.`vyrobce` (
  `idvyrobce` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(100) NOT NULL,
  `popis` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idvyrobce`),
  UNIQUE INDEX `idvyrobce_UNIQUE` (`idvyrobce` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestralka`.`produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestralka`.`produkt` (
  `idprodukt` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(100) NOT NULL,
  `popis` VARCHAR(200) NOT NULL,
  `cena` INT NOT NULL,
  `sleva` INT NOT NULL,
  `v_nabidce` TINYINT NOT NULL,
  `platnost` TINYINT NOT NULL,
  `fotka` BLOB NULL,
  `vyrobce_idvyrobce` INT NOT NULL,
  PRIMARY KEY (`idprodukt`, `vyrobce_idvyrobce`),
  INDEX `fk_produkt_vyrobce_idx` (`vyrobce_idvyrobce` ASC) VISIBLE,
  UNIQUE INDEX `idprodukt_UNIQUE` (`idprodukt` ASC) VISIBLE,
  CONSTRAINT `fk_produkt_vyrobce`
    FOREIGN KEY (`vyrobce_idvyrobce`)
    REFERENCES `semestralka`.`vyrobce` (`idvyrobce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestralka`.`nakoupena_polozka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestralka`.`nakoupena_polozka` (
  `idnakoupena_polozka` INT GENERATED ALWAYS AS (),
  `mnozstvi` INT NOT NULL,
  `produkt_idprodukt` INT NOT NULL,
  PRIMARY KEY (`idnakoupena_polozka`, `produkt_idprodukt`),
  UNIQUE INDEX `idnakoupena_polozka_UNIQUE` (`idnakoupena_polozka` ASC) VISIBLE,
  INDEX `fk_nakoupena_polozka_produkt1_idx` (`produkt_idprodukt` ASC) VISIBLE,
  CONSTRAINT `fk_nakoupena_polozka_produkt1`
    FOREIGN KEY (`produkt_idprodukt`)
    REFERENCES `semestralka`.`produkt` (`idprodukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestralka`.`uzivatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestralka`.`uzivatel` (
  `iduzivatel` INT GENERATED ALWAYS AS (),
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `heslo` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(100) NOT NULL,
  `admin` TINYINT NULL,
  PRIMARY KEY (`iduzivatel`),
  UNIQUE INDEX `iduzivatel_UNIQUE` (`iduzivatel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestralka`.`doprava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestralka`.`doprava` (
  `iddoprava` INT GENERATED ALWAYS AS (),
  `popis` VARCHAR(45) NOT NULL,
  `cena` INT NOT NULL,
  PRIMARY KEY (`iddoprava`),
  UNIQUE INDEX `iddoprava_UNIQUE` (`iddoprava` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestralka`.`platba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestralka`.`platba` (
  `idplatba` INT GENERATED ALWAYS AS (),
  `popis` VARCHAR(45) NOT NULL,
  `prevod` INT NOT NULL,
  PRIMARY KEY (`idplatba`),
  UNIQUE INDEX `idplatba_UNIQUE` (`idplatba` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestralka`.`nakup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestralka`.`nakup` (
  `idnakup` INT GENERATED ALWAYS AS (),
  `poznamka` VARCHAR(100) NULL,
  `stav` TINYINT NOT NULL,
  `datum_vytvoreni` DATETIME NOT NULL,
  `uzivatel_iduzivatel` INT NOT NULL,
  `nakoupena_polozka_idnakoupena_polozka` INT NOT NULL,
  `doprava_iddoprava` INT NOT NULL,
  `platba_idplatba` INT NOT NULL,
  PRIMARY KEY (`idnakup`, `uzivatel_iduzivatel`, `nakoupena_polozka_idnakoupena_polozka`, `doprava_iddoprava`, `platba_idplatba`),
  UNIQUE INDEX `idnakup_UNIQUE` (`idnakup` ASC) VISIBLE,
  INDEX `fk_nakup_uzivatel1_idx` (`uzivatel_iduzivatel` ASC) VISIBLE,
  INDEX `fk_nakup_nakoupena_polozka1_idx` (`nakoupena_polozka_idnakoupena_polozka` ASC) VISIBLE,
  INDEX `fk_nakup_doprava1_idx` (`doprava_iddoprava` ASC) VISIBLE,
  INDEX `fk_nakup_platba1_idx` (`platba_idplatba` ASC) VISIBLE,
  CONSTRAINT `fk_nakup_uzivatel1`
    FOREIGN KEY (`uzivatel_iduzivatel`)
    REFERENCES `semestralka`.`uzivatel` (`iduzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nakup_nakoupena_polozka1`
    FOREIGN KEY (`nakoupena_polozka_idnakoupena_polozka`)
    REFERENCES `semestralka`.`nakoupena_polozka` (`idnakoupena_polozka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nakup_doprava1`
    FOREIGN KEY (`doprava_iddoprava`)
    REFERENCES `semestralka`.`doprava` (`iddoprava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nakup_platba1`
    FOREIGN KEY (`platba_idplatba`)
    REFERENCES `semestralka`.`platba` (`idplatba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestralka`.`komentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestralka`.`komentar` (
  `idkomentar` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NOT NULL,
  `uzivatel_iduzivatel` INT NOT NULL,
  `produkt_idprodukt` INT NOT NULL,
  `vyrobce_idvyrobce` INT NOT NULL,
  PRIMARY KEY (`idkomentar`),
  UNIQUE INDEX `idkomentar_UNIQUE` (`idkomentar` ASC) VISIBLE,
  INDEX `fk_komentar_uzivatel1_idx` (`uzivatel_iduzivatel` ASC) VISIBLE,
  INDEX `fk_komentar_produkt1_idx` (`produkt_idprodukt` ASC) VISIBLE,
  INDEX `fk_komentar_vyrobce1_idx` (`vyrobce_idvyrobce` ASC) VISIBLE,
  CONSTRAINT `fk_komentar_uzivatel1`
    FOREIGN KEY (`uzivatel_iduzivatel`)
    REFERENCES `semestralka`.`uzivatel` (`iduzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_komentar_produkt1`
    FOREIGN KEY (`produkt_idprodukt`)
    REFERENCES `semestralka`.`produkt` (`idprodukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_komentar_vyrobce1`
    FOREIGN KEY (`vyrobce_idvyrobce`)
    REFERENCES `semestralka`.`vyrobce` (`idvyrobce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
CREATE TABLE `semestralka`.`typ` ( `idtyp` INT NOT NULL AUTO_INCREMENT , `popis` VARCHAR(30) NOT NULL , PRIMARY KEY (`idtyp`), UNIQUE (`popis`)) ENGINE = InnoDB;
ALTER TABLE `produkt` ADD `typ_idtyp` INT NOT NULL AFTER `vyrobce_idvyrobce`;
ALTER TABLE produkt ADD FOREIGN KEY (typ_idtyp) REFERENCES typ (idtyp)